### ISSUE TITLE
Some sort of bitrate related bug

### ISSUE THREAD

**Issue by sam0x17** [ptr727/PlexCleaner#146] opened 2023-03-08 04:29 UTC
I have some mkv files that throw this error when I try to run them through plex cleaner:

```
 ---> (Inner Exception #4) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PlexCleaner.BitrateInfo.Calculate(List`1 packetList, Int32 videoStream, Int32 audioStream, Int32 threshold) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/BitrateInfo.cs:line 0
   at PlexCleaner.ProcessFile.GetBitrateInfo(BitrateInfo& bitrateInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1497
   at PlexCleaner.ProcessFile.VerifyBitrate() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1067
   at PlexCleaner.ProcessFile.Verify(Boolean& modified) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 957
   at PlexCleaner.Process.ProcessFile(String fileName, Boolean& modified, States& state, String& processName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 430
   at PlexCleaner.Process.<>c__DisplayClass5_0.<ProcessFiles>b__0(String fileName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 177
   at PlexCleaner.Process.<>c__DisplayClass16_0.<ProcessFilesDriver>b__1(IGrouping`2 keyPair) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 736
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---
```

My workaround right now is to handbrake them manually first, but I'm guessing this might be a simple index out of bounds fix

**Comment by ptr727** [comment] 2023-03-08 04:58
I think this may already be fixed in beta 3.0, I also discovered some media files where the PTS/DTS timestamps were negative, breaking the bitrate calculation logic.
Can you try out beta 3 on the develop branch?

**Comment by sam0x17** [comment] 2023-03-09 04:25
I unfortunately don't have the originals anymore as I already handbraked them

**Comment by ptr727** [comment] 2023-03-09 05:33
Ok, open a new issue if it happens again with v3.

**Comment by sam0x17** [comment] 2023-05-01 12:52
I have another set of files exhibiting this behavior on the latest 3.x beta:

```
 ---> (Inner Exception #4) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PlexCleaner.BitrateInfo.Calculate(List`1 packetList, Int32 videoStream, Int32 audioStream, Int32 threshold) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/BitrateInfo.cs:line 0
   at PlexCleaner.ProcessFile.GetBitrateInfo(BitrateInfo& bitrateInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1497
   at PlexCleaner.ProcessFile.VerifyBitrate() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1067
   at PlexCleaner.ProcessFile.Verify(Boolean& modified) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 957
   at PlexCleaner.Process.ProcessFile(String fileName, Boolean& modified, States& state, String& processName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 430
   at PlexCleaner.Process.<>c__DisplayClass5_0.<ProcessFiles>b__0(String fileName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 177
   at PlexCleaner.Process.<>c__DisplayClass16_0.<ProcessFilesDriver>b__1(IGrouping`2 keyPair) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 736
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---
```

**Comment by sam0x17** [comment] 2023-05-01 12:56
and handbrake re-encodes them properly

**Comment by ptr727** [comment] 2023-05-01 14:13
Can you share the file with me please?

**Comment by sam0x17** [comment] 2023-05-01 14:15
Yeah can I send to your commit email?

**Comment by ptr727** [comment] 2023-05-01 14:21
> Yeah can I send to your commit email?

Please email to pieter at viljoen dot com.

**Comment by ptr727** [comment] 2023-05-06 19:35
Could not reproduce bitrate calculation error in v3 using user provided media file.  
Did add settings file validation and better cover art handling based on user's config file.

**Closed by ptr727** 2023-05-06 19:35 UTC
Labels: bug
